sudo: false
language: python

# To turn off cached miniconda, cython files and compiler cache comment out the
# USE_CACHE=true line for the build in the matrix below. To delete caches go to
# https://travis-ci.org/OWNER/REPOSITORY/caches or run
# travis cache --delete inside the project directory from the travis command line client
# The cash directories will be deleted if anything in ci/ changes in a commit
cache:
 directories:
  - $HOME/miniconda # miniconda cache
  - $HOME/.cache # cython cache
  - $HOME/.ccache # compiler cache

env:
  global:

  # pandas-docs-travis GH
  - secure: "YvvTc+FrSYHgdxqoxn9s8VOaCWjvZzlkaf6k55kkmQqCYR9dPiLMsot1F96/N7o3YlD1s0znPQCak93Du8HHi/8809zAXloTaMSZrWz4R4qn96xlZFRE88O/w/Z1t3VVYpKX3MHlCggBc8MtXrqmvWKJMAqXyysZ4TTzoiJDPvE="

git:
    # for cloning
    depth: 1000

matrix:
    fast_finish: true
    include:
    - language: objective-c
      os: osx
      compiler: clang
      osx_image: xcode6.4
      env:
        - PYTHON_VERSION=3.5
        - JOB_NAME: "35_osx"
        - TEST_ARGS="--skip-slow --skip-network"
        - BUILD_TYPE=conda
        - JOB_TAG=_OSX
        - TRAVIS_PYTHON_VERSION=3.5
        - CACHE_NAME="35_osx"
        - USE_CACHE=true
    - python: 2.7
      env:
        - PYTHON_VERSION=2.7
        - JOB_NAME: "27_slow_nnet_LOCALE"
        - TEST_ARGS="--only-slow --skip-network"
        - LOCALE_OVERRIDE="zh_CN.UTF-8"
        - FULL_DEPS=true
        - JOB_TAG=_LOCALE
        - CACHE_NAME="27_slow_nnet_LOCALE"
        - USE_CACHE=true
      addons:
        apt:
          packages:
          - language-pack-zh-hans
    - python: 2.7
      env:
        - PYTHON_VERSION=2.7
        - JOB_NAME: "27_nslow"
        - TEST_ARGS="--skip-slow"
        - FULL_DEPS=true
        - CLIPBOARD_GUI=gtk2
        - LINT=true
        - CACHE_NAME="27_nslow"
        - USE_CACHE=true
      addons:
        apt:
          packages:
          - python-gtk2
    - python: 3.5
      env:
        - PYTHON_VERSION=3.5
        - JOB_NAME: "35_nslow"
        - TEST_ARGS="--skip-slow --skip-network"
        - FULL_DEPS=true
        - CLIPBOARD=xsel
        - COVERAGE=true
        - CACHE_NAME="35_nslow"
#        - USE_CACHE=true # Don't use cache for 35_nslow
      addons:
        apt:
          packages:
          - xsel
    - python: 3.6
      env:
        - PYTHON_VERSION=3.6
        - JOB_NAME: "36"
        - TEST_ARGS="--skip-slow --skip-network"
        - PANDAS_TESTING_MODE="deprecate"
        - CONDA_FORGE=true
      addons:
        apt:
          packages:
          - libatlas-base-dev
          - gfortran
#    In allow_failures
    - python: 2.7
      env:
        - PYTHON_VERSION=2.7
        - JOB_NAME: "27_slow"
        - JOB_TAG=_SLOW
        - TEST_ARGS="--only-slow --skip-network"
        - FULL_DEPS=true
        - CACHE_NAME="27_slow"
        - USE_CACHE=true
#    In allow_failures
    - python: 2.7
      env:
        - PYTHON_VERSION=2.7
        - JOB_NAME: "27_build_test_conda"
        - JOB_TAG=_BUILD_TEST
        - TEST_ARGS="--skip-slow"
        - FULL_DEPS=true
        - BUILD_TEST=true
        - CACHE_NAME="27_build_test_conda"
        - USE_CACHE=true
#    In allow_failures
    - python: 3.5
      env:
        - PYTHON_VERSION=3.5
        - JOB_NAME: "35_numpy_dev"
        - JOB_TAG=_NUMPY_DEV
        - TEST_ARGS="--skip-slow --skip-network"
        - PANDAS_TESTING_MODE="deprecate"
        - CACHE_NAME="35_numpy_dev"
        - USE_CACHE=true
      addons:
        apt:
          packages:
          - libatlas-base-dev
          - gfortran
#    In allow_failures
    - python: 3.5
      env:
        - PYTHON_VERSION=3.5
        - JOB_NAME: "doc_build"
        - FULL_DEPS=true
        - DOC_BUILD=true
        - JOB_TAG=_DOC_BUILD
        - CACHE_NAME="doc_build"
        - USE_CACHE=true
    allow_failures:
      - python: 2.7
        env:
        - PYTHON_VERSION=2.7
        - JOB_NAME: "27_slow"
        - JOB_TAG=_SLOW
        - TEST_ARGS="--only-slow --skip-network"
        - FULL_DEPS=true
        - CACHE_NAME="27_slow"
        - USE_CACHE=true
      - python: 2.7
        env:
        - PYTHON_VERSION=2.7
        - JOB_NAME: "27_build_test_conda"
        - JOB_TAG=_BUILD_TEST
        - TEST_ARGS="--skip-slow"
        - FULL_DEPS=true
        - BUILD_TEST=true
        - CACHE_NAME="27_build_test_conda"
        - USE_CACHE=true
      - python: 3.5
        env:
          - PYTHON_VERSION=3.5
          - JOB_NAME: "35_numpy_dev"
          - JOB_TAG=_NUMPY_DEV
          - TEST_ARGS="--skip-slow --skip-network"
          - PANDAS_TESTING_MODE="deprecate"
          - CACHE_NAME="35_numpy_dev"
          - USE_CACHE=true
        addons:
          apt:
            packages:
            - libatlas-base-dev
            - gfortran
      - python: 3.5
        env:
        - PYTHON_VERSION=3.5
        - JOB_NAME: "doc_build"
        - FULL_DEPS=true
        - DOC_BUILD=true
        - JOB_TAG=_DOC_BUILD
        - CACHE_NAME="doc_build"
        - USE_CACHE=true

before_install:
  - echo "before_install"
  - source ci/travis_process_gbq_encryption.sh
  - echo $VIRTUAL_ENV
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - df -h
  - date
  - pwd
  - uname -a
  - python -V
  - git --version
  - git tag
  - ci/before_install_travis.sh
  - export DISPLAY=:99.0

install:
  - echo "install start"
  - ci/check_cache.sh
  - ci/prep_cython_cache.sh
  - ci/install_travis.sh
  - ci/submit_cython_cache.sh
  - echo "install done"

before_script:
  - source activate pandas && pip install codecov
  - ci/install_db_travis.sh

script:
  - echo "script start"
  - ci/run_build_docs.sh
  - ci/script_single.sh
  - ci/script_multi.sh
  - ci/lint.sh
  - echo "script done"

after_success:
  - source activate pandas && codecov

after_script:
  - echo "after_script start"
  - ci/install_test.sh
  - source activate pandas && python -c "import pandas; pandas.show_versions();"
  - ci/print_skipped.py /tmp/single.xml
  - ci/print_skipped.py /tmp/multiple.xml
  - echo "after_script done"
