language: python

python:
  - 2.6

env:
  global:
    - NOSE_ARGS="not slow" UPLOAD=true

matrix:
  include:
    - python: 2.7
      env: NOSE_ARGS="slow and not network"  LOCALE_OVERRIDE="zh_CN.GB18030" FULL_DEPS=true JOB_TAG=_LOCALE
    - python: 2.7
      env: NOSE_ARGS="not slow" FULL_DEPS=true
    - python: 3.2
      env: NOSE_ARGS="not slow" FULL_DEPS=true
    - python: 3.3
      env: NOSE_ARGS="not slow" FULL_DEPS=true

# allow importing from site-packages,
# so apt-get python-x works for system pythons
# That's 2.7/3.2 on Ubuntu 12.04
virtualenv:
  system_site_packages: true

before_install:
  - echo "Waldo1"
  - echo $VIRTUAL_ENV
  - df
  - date
  # - export PIP_ARGS=-q # comment this this to debug travis install issues
  # - export APT_ARGS=-qq # comment this to debug travis install issues
  # - set -x # enable this to see bash commands
  - export ZIP_FLAGS=-q # comment this to debug travis install issues
  - ci/before_install.sh
  - python -V

install:
  - echo "Waldo2"
  - ci/install.sh

before_script:
  - mysql -e 'create database pandas_nosetest;'

script:
  - echo "Waldo3"
  - ci/script.sh

after_script:
  - ci/print_versions.py
