language: python

python:
  - 2.6
  - 3.3

env:
  global:
    - NOSE_ARGS="not slow" # need at least this so travis page will show env column

matrix:
  include:
    - python: 2.7
      env: NOSE_ARGS="not network"  LOCALE_OVERRIDE="zh_CN.GB18030"
    - python: 2.7
      env: NOSE_ARGS="not slow" FULL_DEPS=true
    - python: 3.2
      env: NOSE_ARGS="not slow" FULL_DEPS=true

# allow importing from site-packages,
# so apt-get python-x works for system pythons
# That's 2.7/3.2 on Ubuntu 12.04
virtualenv:
  system_site_packages: true

before_install:
  - echo "Waldo1"
  - echo $VIRTUAL_ENV
  - date
  - export PIP_ARGS=-q # comment this this to debug travis install issues
  - export APT_ARGS=-qq # comment this to debug travis install issues
  # - set -x # enable this to see bash commands
  - source ci/before_install.sh # we need to source this to bring in the env
  - python -V

install:
  - echo "Waldo2"
  - ci/install.sh

script:
  - echo "Waldo3"
  - ci/script.sh

after_script:
  - ci/print_versions.py
