
language: python

env:

  global:
  # scatterci API key
  #- secure: "Bx5umgo6WjuGY+5XFa004xjCiX/vq0CyMZ/ETzcs7EIBI1BE/0fIDXOoWhoxbY9HPfdPGlDnDgB9nGqr5wArO2s+BavyKBWg6osZ3dmkfuJPMOWeyCa92EeP+sfKw8e5HSU5MizW9e319wHWOF/xkzdHR7T67Qd5erhv91x4DnQ="
  # ironcache API key
  - secure: "e4eEFn9nDQc3Xa5BWYkzfX37jaWVq89XidVX+rcCNEr5OlOImvveeXnF1IzbRXznH4Sv0YsLwUd8RGUWOmyCvkONq/VJeqCHWtTMyfaCIdqSyhIP9Odz8r9ahch+Y0XFepBey92AJHmlnTh+2GjCDgIiqq4fzglojnp56Vg1ojA="
  - secure: "CjmYmY5qEu3KrvMtel6zWFEtMq8ORBeS1S1odJHnjQpbwT1KY2YFZRVlLphfyDQXSz6svKUdeRrCNp65baBzs3DQNA8lIuXGIBYFeJxqVGtYAZZs6+TzBPfJJK798sGOj5RshrOJkFG2rdlWNuTq/XphI0JOrN3nPUkRrdQRpAw="
  # pandas-docs-bot GH
  - secure: "PCzUFR8CHmw9lH84p4ygnojdF7Z8U5h7YfY0RyT+5K/aiQ1ZTU3ZkDTPI0/rR5FVMxsEEKEQKMcc5fvqW0PeD7Q2wRmluloKgT9w4EVEJ1ppKf7lITPcvZR2QgVOvjv4AfDtibLHFNiaSjzoqyJVjM4igjOu8WTlF3JfZcmOQjQ="

matrix:
    fast_finish: true
    include:
    - python: 2.6
      env:
      - NOSE_ARGS="not slow and not network and not disabled"
      - CLIPBOARD=xclip
      - LOCALE_OVERRIDE="it_IT.UTF-8"
      - BUILD_TYPE=conda
      - JOB_NAME: "26_nslow_nnet"
      - INSTALL_TEST=true
    - python: 2.7
      env:
      - NOSE_ARGS="slow and not network and not disabled"
      - LOCALE_OVERRIDE="zh_CN.GB18030"
      - FULL_DEPS=true
      - JOB_TAG=_LOCALE
      - BUILD_TYPE=conda
      - JOB_NAME: "27_slow_nnet_LOCALE"
    - python: 2.7
      env:
      - NOSE_ARGS="not slow and not disabled"
      - FULL_DEPS=true
      - CLIPBOARD_GUI=gtk2
      - BUILD_TYPE=conda
      - JOB_NAME: "27_build_test"
      - JOB_TAG=_BUILD_TEST
      - BUILD_TEST=true
    - python: 2.7
      env:
      - NOSE_ARGS="not slow and not disabled"
      - FULL_DEPS=true
      - CLIPBOARD_GUI=gtk2
      - BUILD_TYPE=pydata
      - JOB_NAME: "27_build_test"
      - JOB_TAG=_BUILD_TEST
      - BUILD_TEST=true
    - python: 2.7
      env:
      - NOSE_ARGS="not slow and not disabled"
      - FULL_DEPS=true
      - CLIPBOARD_GUI=gtk2
      - BUILD_TYPE=conda
      - JOB_NAME: "27_nslow"
      - DOC_BUILD=true # if rst files were changed, build docs in parallel with tests
    - python: 2.7
      env:
      - NOSE_ARGS="slow and not network and not disabled"
      - FULL_DEPS=true
      - JOB_TAG=_SLOW
      - BUILD_TYPE=conda
      - JOB_NAME: "27_slow"
    - python: 3.3
      env:
      - NOSE_ARGS="not slow and not disabled"
      - FULL_DEPS=true
      - CLIPBOARD=xsel
      - BUILD_TYPE=conda
      - JOB_NAME: "33_nslow"
    - python: 3.4
      env:
      - NOSE_ARGS="not slow and not disabled"
      - FULL_DEPS=true
      - CLIPBOARD=xsel
      - BUILD_TYPE=conda
      - JOB_NAME: "34_nslow"
    - python: 3.4
      env:
      - NOSE_ARGS="slow and not network and not disabled"
      - FULL_DEPS=true
      - JOB_TAG=_SLOW
      - CLIPBOARD=xsel
      - BUILD_TYPE=conda
      - JOB_NAME: "34_slow"
    - python: 2.7
      env:
      - EXPERIMENTAL=true
      - NOSE_ARGS="not slow and not network and not disabled"
      - JOB_NAME: "27_numpy_master"
      - JOB_TAG=_NUMPY_DEV_master
      - NUMPY_BUILD=master
      - BUILD_TYPE=pydata
      - PANDAS_TESTING_MODE="deprecate"
    allow_failures:
      - python: 2.7
        env:
        - NOSE_ARGS="slow and not network and not disabled"
        - FULL_DEPS=true
        - JOB_TAG=_SLOW
        - BUILD_TYPE=conda
        - JOB_NAME: "27_slow"
      - python: 3.4
        env:
        - NOSE_ARGS="slow and not network and not disabled"
        - FULL_DEPS=true
        - JOB_TAG=_SLOW
        - CLIPBOARD=xsel
        - BUILD_TYPE=conda
        - JOB_NAME: "34_slow"
      - python: 2.7
        env:
        - EXPERIMENTAL=true
        - NOSE_ARGS="not slow and not network and not disabled"
        - JOB_NAME: "27_numpy_master"
        - JOB_TAG=_NUMPY_DEV_master
        - NUMPY_BUILD=master
        - BUILD_TYPE=pydata
        - PANDAS_TESTING_MODE="deprecate"
      - python: 2.7
        env:
        - NOSE_ARGS="not slow and not disabled"
        - FULL_DEPS=true
        - CLIPBOARD_GUI=gtk2
        - BUILD_TYPE=conda
        - JOB_NAME: "27_build_test"
        - JOB_TAG=_BUILD_TEST
        - BUILD_TEST=true
      - python: 2.7
        env:
        - NOSE_ARGS="not slow and not disabled"
        - FULL_DEPS=true
        - CLIPBOARD_GUI=gtk2
        - BUILD_TYPE=pydata
        - JOB_NAME: "27_build_test"
        - JOB_TAG=_BUILD_TEST
        - BUILD_TEST=true

before_install:
  - echo "before_install"
  - echo $VIRTUAL_ENV
  - export PATH="$HOME/miniconda/bin:$PATH"
  - sudo apt-get install ccache
  - df -h
  - date
  - pwd
  - uname -a
  - python -V
  - ci/before_install.sh
  # Xvfb stuff for clipboard functionality; see the travis-ci documentation
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - echo "install"
  - ci/prep_ccache.sh
  - ci/install_${BUILD_TYPE}.sh
  - ci/submit_ccache.sh

before_script:
  - mysql -e 'create database pandas_nosetest;'
  - psql -c 'create database pandas_nosetest;' -U postgres

script:
  - echo "script"
  - ci/run_build_docs.sh &
  - ci/script.sh
# nothing here, or failed tests won't fail travis

after_script:
  - ci/install_test.sh
  - if [ -f /tmp/doc.log ]; then cat /tmp/doc.log; fi
  - source activate pandas && ci/print_versions.py
  - ci/print_skipped.py /tmp/nosetests.xml
  - ci/after_script.sh
