language: python

env:
  global:
  # scatterci API key
  - secure: "Bx5umgo6WjuGY+5XFa004xjCiX/vq0CyMZ/ETzcs7EIBI1BE/0fIDXOoWhoxbY9HPfdPGlDnDgB9nGqr5wArO2s+BavyKBWg6osZ3dmkfuJPMOWeyCa92EeP+sfKw8e5HSU5MizW9e319wHWOF/xkzdHR7T67Qd5erhv91x4DnQ="
  # ironcache API key
  - secure: "TWGKPL4FGtWjCQ427QrSffaQBSCPy1QzPdhtYKAW9AlDo/agdp9RyZRQr8WTlyZ5AOG18X8MDdi0EcpFnyfDNd4thCLyZOntxwltlVV2yNNvnird3XRKUV1F2DD42L64wna04M2KYxpCKhEQ84gEnCH1DGD4g1NnR6fYuEYNSTU="
  - secure: "NvgIWe14pv4SJ5BQhw6J0zIpCTFH4fVpzr9pRzM2tD8yf/3cspX3uyXTt4owiqtjoQ3aQGNnhWtVlmSwlgJrwu7KUaE9IPtlsENYDniAj2oJgejjx02d367pHtMB/9e3+4b2fWUsFNJgWw0ordiIT0p1lzHRdQ9ut4l/Yn/lkJs="
  - secure: "D3ASNRu32pV79lv/Nl0dBm2ldZiTgbb6boOrN0SzIKsQU3yBwedpqX6EI6KjpVg17lGhhhFXGzL2Gz1qjU3/+m6aMvekxHgpfuc0AlEFCEqenWPxIdDDrUkdfJoCvfQQPd5oxChfHgqaEDLjuqHy1ZEgnJ2/L/6dwZ4fUt62hMk="
  # pandas-docs-bot GH
  - secure: "PCzUFR8CHmw9lH84p4ygnojdF7Z8U5h7YfY0RyT+5K/aiQ1ZTU3ZkDTPI0/rR5FVMxsEEKEQKMcc5fvqW0PeD7Q2wRmluloKgT9w4EVEJ1ppKf7lITPcvZR2QgVOvjv4AfDtibLHFNiaSjzoqyJVjM4igjOu8WTlF3JfZcmOQjQ="

matrix:
    include:
    - python: 2.6
      env:
      - NOSE_ARGS="not slow and not network"
      - CLIPBOARD=xclip
      - LOCALE_OVERRIDE="it_IT.UTF-8"
      - JOB_NAME: "26_nslow_nnet" # ScatterCI Build name, 20 chars max
    - python: 2.7
      env:
      - NOSE_ARGS="slow and not network"
      - LOCALE_OVERRIDE="zh_CN.GB18030"
      - FULL_DEPS=true
      - JOB_TAG=_LOCALE
      - JOB_NAME: "27_slow_nnet_LOCALE" # ScatterCI Build name, 20 chars max
    - python: 2.7
      env:
      - NOSE_ARGS="not slow"
      - FULL_DEPS=true
      - CLIPBOARD_GUI=gtk2
      - JOB_NAME: "27_nslow" # ScatterCI Build name, 20 chars max
      - DOC_BUILD=true # if rst files were changed, build docs in parallel with tests
    - python: 3.2
      env:
      - NOSE_ARGS="not slow"
      - FULL_DEPS=true
      - CLIPBOARD_GUI=qt4
      - JOB_NAME: "32_nslow"  # ScatterCI Build name, 20 chars max
    - python: 3.3
      env:
      - NOSE_ARGS="not slow"
      - FULL_DEPS=true
      - CLIPBOARD=xsel
      - JOB_NAME: "33_nslow"  # ScatterCI Build name, 20 chars max


# allow importing from site-packages,
# so apt-get python-x works for system pythons
# That's 2.7/3.2 on Ubuntu 12.04
virtualenv:
  system_site_packages: true

before_install:
  - echo "before_install"
  - echo $VIRTUAL_ENV
  - df -h
  - date
  - pwd
  - uname -a
  - python -V
  - ci/before_install.sh
  # Xvfb stuff for clipboard functionality; see the travis-ci documentation
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - echo "install"
  - ci/prep_ccache.sh
  - ci/install.sh
  - ci/submit_ccache.sh

before_script:
  - mysql -e 'create database pandas_nosetest;'

script:
  - echo "script"
  - ci/script.sh
  - if [ -f /tmp/doc.log ]; then cat /tmp/doc.log; fi

after_script:
  - ci/print_versions.py
  - ci/print_skipped.py /tmp/nosetests.xml
  - ci/after_script.sh
