language: python

python:
  - 2.6
  - 2.7
  - 3.1
  - 3.2

install:
  - pip install --use-mirrors cython numpy nose pytz python-dateutil

script:
  - python setup.py build_ext install
  - nosetests --exe -w /tmp pandas.tests
