language: python

python:
  - 2.6

matrix:
    include:
    - python: 2.6
      env:
      - NOSE_ARGS="not slow and not network"
      - CLIPBOARD=xclip
      - LOCALE_OVERRIDE="it_IT.UTF-8"
      - secure: "Bx5umgo6WjuGY+5XFa004xjCiX/vq0CyMZ/ETzcs7EIBI1BE/0fIDXOoWhoxbY9HPfdPGlDnDgB9nGqr5wArO2s+BavyKBWg6osZ3dmkfuJPMOWeyCa92EeP+sfKw8e5HSU5MizW9e319wHWOF/xkzdHR7T67Qd5erhv91x4DnQ="
      - JOB_NAME: "26_nslow_nnet" # ScatterCI Build name, 20 chars max
    - python: 2.7
      env:
      - NOSE_ARGS="slow and not network"
      - LOCALE_OVERRIDE="zh_CN.GB18030"
      - FULL_DEPS=true
      - JOB_TAG=_LOCALE
      - secure: "Bx5umgo6WjuGY+5XFa004xjCiX/vq0CyMZ/ETzcs7EIBI1BE/0fIDXOoWhoxbY9HPfdPGlDnDgB9nGqr5wArO2s+BavyKBWg6osZ3dmkfuJPMOWeyCa92EeP+sfKw8e5HSU5MizW9e319wHWOF/xkzdHR7T67Qd5erhv91x4DnQ="
      - JOB_NAME: "27_slow_nnet_LOCALE" # ScatterCI Build name, 20 chars max
    - python: 2.7
      env:
      - NOSE_ARGS="not slow"
      - FULL_DEPS=true
      - CLIPBOARD_GUI=gtk2
      - secure: "Bx5umgo6WjuGY+5XFa004xjCiX/vq0CyMZ/ETzcs7EIBI1BE/0fIDXOoWhoxbY9HPfdPGlDnDgB9nGqr5wArO2s+BavyKBWg6osZ3dmkfuJPMOWeyCa92EeP+sfKw8e5HSU5MizW9e319wHWOF/xkzdHR7T67Qd5erhv91x4DnQ="
      - JOB_NAME: "27_nslow" # ScatterCI Build name, 20 chars max
    - python: 3.2
      env:
      - NOSE_ARGS="not slow"
      - FULL_DEPS=true
      - CLIPBOARD_GUI=qt4
      - secure: "Bx5umgo6WjuGY+5XFa004xjCiX/vq0CyMZ/ETzcs7EIBI1BE/0fIDXOoWhoxbY9HPfdPGlDnDgB9nGqr5wArO2s+BavyKBWg6osZ3dmkfuJPMOWeyCa92EeP+sfKw8e5HSU5MizW9e319wHWOF/xkzdHR7T67Qd5erhv91x4DnQ="
      - JOB_NAME: "32_nslow"  # ScatterCI Build name, 20 chars max
    - python: 3.3
      env:
      - NOSE_ARGS="not slow"
      - FULL_DEPS=true
      - CLIPBOARD=xsel
      - secure: "Bx5umgo6WjuGY+5XFa004xjCiX/vq0CyMZ/ETzcs7EIBI1BE/0fIDXOoWhoxbY9HPfdPGlDnDgB9nGqr5wArO2s+BavyKBWg6osZ3dmkfuJPMOWeyCa92EeP+sfKw8e5HSU5MizW9e319wHWOF/xkzdHR7T67Qd5erhv91x4DnQ="
      - JOB_NAME: "33_nslow"  # ScatterCI Build name, 20 chars max
    exclude:
    - python: 2.6

# allow importing from site-packages,
# so apt-get python-x works for system pythons
# That's 2.7/3.2 on Ubuntu 12.04
virtualenv:
  system_site_packages: true

before_install:
  - echo "before_install"
  - echo $VIRTUAL_ENV
  - df -h
  - date
  - uname -a
  - ci/before_install.sh
  - python -V
  # Xvfb stuff for clipboard functionality; see the travis-ci documentation
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - echo "install"
  - ci/install.sh

before_script:
  - mysql -e 'create database pandas_nosetest;'

script:
  - echo "script"
  - ci/script.sh

after_script:
  - ci/print_versions.py
  - ci/print_skipped.py /tmp/nosetests.xml
  - ci/after_script.sh