name: pandas-dev
channels:
  - defaults
  - conda-forge
dependencies:
  # required
  - NumPy
  - python=3
  - python-dateutil>=2.5.0
  - pytz

  # development
  - Cython>=0.28.2
  - flake8
  - flake8-comprehensions
  - flake8-rst
  - hypothesis>=3.58.0
  - isort
  - moto
  - pytest>=3.6
  - setuptools>=24.2.0
  - sphinx
  - sphinxcontrib-spelling

  # optional
  - beautifulsoup4>=4.2.1
  - blosc
  - bottleneck>=1.2.0
  - fastparquet>=0.1.2
  - gcsfs
  - html5lib
  - ipython>=5.6.0
  - ipykernel
  - jinja2
  - lxml
  - matplotlib>=2.0.0
  - nbsphinx
  - numexpr>=2.6.1
  - openpyxl
  - pyarrow>=0.7.0
  - pymysql
  - pytables>=3.4.2
  - pytest-cov
  - pytest-xdist
  - s3fs
  - scipy>=0.18.1
  - seaborn
  - sqlalchemy
  - statsmodels
  - xarray
  - xlrd
  - xlsxwriter
  - xlwt
