name: pandas
channels:
  - defaults
  - conda-forge
dependencies:
  - blosc
  - bottleneck
  - fastparquet
  - feather-format
  - matplotlib
  - numexpr
  - numpy=1.14*
  - openpyxl
  - pyarrow
  - pytables
  - python-dateutil
  - python=3.6.*
  - pytz
  - scipy
  - thrift=0.10*
  - xlrd
  - xlsxwriter
  - xlwt
  # universal
  - cython>=0.28.2
  - pytest
  - pytest-xdist
  - hypothesis>=3.58.0
